# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_number', models.CharField(max_length=255, verbose_name='Asset Number')),
                ('_type', models.CharField(choices=[('V', 'Vehicle'), ('O', 'Other')], max_length=255, verbose_name='Asset Type')),
                ('item', models.CharField(max_length=255, verbose_name='Item')),
                ('serial_number', models.CharField(max_length=255, verbose_name='Serial Number')),
                ('purchase_date', models.DateField(verbose_name='Purchase Date')),
                ('purchase_price', models.CharField(blank=True, max_length=255, null=True, verbose_name='Purchase Price')),
                ('currency', models.CharField(choices=[('ZMK', 'ZMK'), ('USD', 'USD'), ('GBP', 'GBP'), ('EUR', 'EUR')], max_length=255, verbose_name='Currency')),
                ('condition', models.CharField(help_text='e.g good, bad etc', max_length=255, verbose_name='Condition')),
                ('comments', models.TextField(verbose_name='Comments on Asset')),
            ],
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Competency Name')),
                ('priority', models.IntegerField(help_text='Priority from 1 to 9, 1 is most prefferd.', verbose_name='Priority')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Department Name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Facility Name')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='JobTitleCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Job Title')),
                ('typ', models.CharField(choices=[('S', 'Saff'), ('V', 'Volunteer'), ('B', 'Both')], max_length=255, verbose_name='Type')),
                ('description', models.TextField(verbose_name='Job Descritpion')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('acronym', models.CharField(max_length=255, verbose_name='Acronym')),
                ('country', models.CharField(choices=[('ZM', 'Zambia'), ('USA', 'United States of America')], max_length=255, verbose_name='Home Country')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone Number')),
                ('website', models.URLField(verbose_name='Website URL')),
                ('Year', models.DateField(blank=True, verbose_name='Date Organization was Founded')),
                ('remarks', models.TextField(verbose_name='Remarks or Comments')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationOfficeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Organization Office Name')),
                ('code', models.CharField(max_length=255, verbose_name='Organization Office Code')),
                ('_type', models.CharField(max_length=255, verbose_name='Organization Office Type')),
                ('Street_address', models.CharField(max_length=255, verbose_name='Organziation Street Adress')),
                ('postcode', models.CharField(max_length=255, verbose_name='Organization POst Code')),
                ('latitude', models.CharField(max_length=255, verbose_name='Organization Office Latitude')),
                ('longitude', models.CharField(max_length=255, verbose_name='Organization Office Longitude')),
                ('Phone_1', models.CharField(max_length=255, verbose_name='Phone line 1')),
                ('Phone_2', models.CharField(max_length=255, verbose_name='Phone line 2')),
                ('email', models.EmailField(max_length=254, verbose_name='Office Email Address')),
                ('remarks', models.TextField(verbose_name='Remarks or Comments')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Organization Sector name')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Organization Type Name')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name')),
                ('initials', models.CharField(blank=True, max_length=255, null=True, verbose_name='Initials')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=255, verbose_name='Gender')),
                ('date_of_birth', models.DateField(verbose_name='Date of birth')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Programme Name')),
                ('Short_title', models.CharField(max_length=255, verbose_name='Short Title / ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('comments', models.TextField(verbose_name='Comments')),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammeStatusChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g pending, active etc', max_length=255, verbose_name='Programe Status Name')),
                ('comments', models.TextField(verbose_name='Comments')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('comments', models.TextField(verbose_name='Comments')),
            ],
        ),
        migrations.CreateModel(
            name='StaffSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Competency')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Person')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Skill')),
            ],
        ),
        migrations.AddField(
            model_name='programme',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.ProgrammeStatusChoices'),
        ),
        migrations.AddField(
            model_name='organization',
            name='_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.OrganizationType'),
        ),
        migrations.AddField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='asset',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Facility'),
        ),
        migrations.AddField(
            model_name='asset',
            name='supplier_donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization'),
        ),
    ]
