# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-26 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disasteremergencybuilding',
            options={'verbose_name': 'DISASTER EMERGENCY BUILDING', 'verbose_name_plural': 'DISASTER EMERGENCY BUILDINGS'},
        ),
        migrations.AlterModelOptions(
            name='healthfacility',
            options={'verbose_name': 'HEALTH FACILITY', 'verbose_name_plural': 'HEALTH FACILITIES'},
        ),
    ]
