# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictCommittee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='District Name')),
                ('co_ordinator', models.CharField(blank=True, max_length=255, null=True, verbose_name='Co-ordinator(Chairperson)')),
                ('gov_depts_repr_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Government Department District Representative One')),
                ('gov_depts_repr_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Government Department District Representative Two')),
                ('gov_depts_repr_3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Government Department District Representative Three')),
                ('gov_depts_repr_4', models.CharField(blank=True, max_length=255, null=True, verbose_name='Government Department District Representative Four')),
                ('gov_depts_repr_5', models.CharField(blank=True, max_length=255, null=True, verbose_name='Government Department District Representative Five')),
                ('gov_depts_repr_6', models.CharField(blank=True, max_length=255, null=True, verbose_name='Government Department District Representative Six')),
                ('gov_depts_repr_7', models.CharField(blank=True, max_length=255, null=True, verbose_name='Government Department District Representative Seven')),
                ('all_parliament_members', models.TextField(blank=True, null=True, verbose_name='All Parliament Members in District')),
                ('zam_red_cross_repr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Zambia Red Cross Representative')),
                ('each_ngo_repr', models.TextField(blank=True, null=True, verbose_name='Each NGO representative')),
                ('rel_org_repr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Religious Organisation Representative')),
                ('zam_chamb_com_repr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Zambia Chamber of Commerce Representative')),
                ('secretary', models.CharField(blank=True, max_length=255, null=True, verbose_name='Secretary')),
                ('co_opted_member', models.TextField(blank=True, null=True, verbose_name='Co-opted/Other Members')),
            ],
            options={
                'verbose_name': 'DISTRICT COMMITTEE',
                'verbose_name_plural': 'DISTRICT COMMITTEES',
            },
        ),
        migrations.CreateModel(
            name='MaizeRequisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date Prepared')),
                ('to', models.CharField(max_length=255, verbose_name='To')),
                ('source', models.CharField(max_length=255, verbose_name='Source(Place)')),
                ('requisition_num', models.CharField(max_length=255, verbose_name='Requisition Number')),
                ('destination', models.CharField(max_length=255, verbose_name='Destination(Place)')),
                ('item_descr', models.CharField(max_length=355, verbose_name='Item Description')),
                ('qty', models.CharField(max_length=255, verbose_name='Quantity (Qty)')),
                ('unit', models.CharField(max_length=255, verbose_name='Unit')),
                ('stock_code', models.CharField(max_length=255, verbose_name='Stock Code')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('prepared_by', models.CharField(max_length=255, verbose_name='Prepared by: (name):')),
                ('prepared_by_signature_status', models.BooleanField(default=0, verbose_name='Prepared by: (signature(signed/pending))')),
                ('approved_by', models.CharField(max_length=255, verbose_name='Approved by: (name):')),
                ('approved_by_signature_status', models.BooleanField(default=0, verbose_name='Approved by: (signature(signed/pending))')),
                ('authorised_by', models.CharField(max_length=255, verbose_name='Authorised by: (name):')),
                ('authorised_by_signature_status', models.BooleanField(default=0, verbose_name='Authorised by: (signature(signed/pending))')),
            ],
            options={
                'verbose_name': 'MAIZE REQUISITION',
                'verbose_name_plural': 'MAIZE REQUISITIONS',
            },
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g  Home Affairs etc', max_length=255, verbose_name='Ministry Name')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'MINISTRY',
                'verbose_name_plural': 'MINISTRIES',
            },
        ),
        migrations.CreateModel(
            name='NationalDisasterManagementConsultativeForum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chairperson', models.CharField(blank=True, max_length=255, null=True, verbose_name='Chairperson')),
                ('Secretariat', models.CharField(blank=True, max_length=255, null=True, verbose_name='Secretariat')),
                ('less_than_10_part_time_members', models.TextField(blank=True, null=True, verbose_name='Not more than Ten Part time Members')),
                ('organizations_representatives', models.TextField(blank=True, null=True, verbose_name='Various Organizational Board Representatives')),
            ],
            options={
                'verbose_name': 'NATIONAL DISASTER MANAGEMENT CONSULTATIVE FORUM',
                'verbose_name_plural': 'NATIONAL DISASTER MANAGEMENT CONSULTATIVE FORUMS',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Province Name')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'PROVINCE',
                'verbose_name_plural': 'PROVINCES',
            },
        ),
        migrations.CreateModel(
            name='ProvincialCommittee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Province Name')),
                ('provincial_ps', models.CharField(max_length=255, verbose_name='Provincial Permanent Secretary(Chairperson)')),
                ('gov_depts_repr_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Government Department Provincial Representative One')),
                ('gov_depts_repr_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Government Department Provincial Representative Two')),
                ('gov_depts_repr_3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Government Department Provincial Representative Three')),
                ('gov_depts_repr_4', models.CharField(blank=True, max_length=255, null=True, verbose_name='Government Department Provincial Representative Four')),
                ('gov_depts_repr_5', models.CharField(blank=True, max_length=255, null=True, verbose_name='Government Department Provincial Representative Five')),
                ('gov_depts_repr_6', models.CharField(blank=True, max_length=255, null=True, verbose_name='Government Department Provincial Representative Six')),
                ('gov_depts_repr_7', models.CharField(blank=True, max_length=255, null=True, verbose_name='Government Department Provincial Representative Seven')),
                ('pri_sector_repr_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Private Sector Representative One')),
                ('pri_sector_repr_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Private Sector Representative Two')),
                ('rel_org_repr_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Religious Organisation Representative One')),
                ('rel_org_repr_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Religious Organisation Representative Two')),
                ('pro_dis_mgnt_cord', models.CharField(blank=True, max_length=255, null=True, verbose_name='Provincial Disaster Management CO-ordinator(Secretary)')),
                ('vice_chairperson', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vice-Chairperson')),
                ('co_ordinator', models.CharField(blank=True, max_length=255, null=True, verbose_name='Co-ordinator(Public Officer)')),
            ],
            options={
                'verbose_name': 'PROVINCIAL COMMITTEE',
                'verbose_name_plural': 'PROVINCIAL COMMITTEES',
            },
        ),
        migrations.CreateModel(
            name='ReliefMaizeDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(blank=True, max_length=255, null=True, verbose_name='DISTRICT')),
                ('quantity', models.CharField(blank=True, max_length=255, null=True, verbose_name='QUANTITY(MT)')),
                ('requisition', models.CharField(blank=True, max_length=255, null=True, verbose_name='REQUISTION #')),
                ('requisition_date', models.DateField(blank=True, max_length=255, null=True, verbose_name='REQUISTION DATE')),
                ('delivery_order_num', models.DateField(blank=True, max_length=255, null=True, verbose_name='DELIVERY ORDER #')),
                ('access_point', models.DateField(blank=True, max_length=255, null=True, verbose_name='ACCESS POINT')),
                ('project_implemting_partner', models.DateField(blank=True, max_length=255, null=True, verbose_name='PROJECT IMPLEMENTING PARTNER')),
                ('mou_number', models.DateField(blank=True, max_length=255, null=True, verbose_name='MOU NUMBER')),
                ('mou_amount', models.DateField(blank=True, max_length=255, null=True, verbose_name='MOU AMOUNT')),
                ('first_50_percent', models.DateField(blank=True, max_length=255, null=True, verbose_name='1st 50%')),
                ('first_50_percent_chq_num', models.DateField(blank=True, max_length=255, null=True, verbose_name='1st 50%\\ CHQ #')),
                ('second_50_percent', models.DateField(blank=True, max_length=255, null=True, verbose_name='2st 50%')),
                ('second_50_percent_chq_num', models.DateField(blank=True, max_length=255, null=True, verbose_name='2st 50%\\ CHQ #')),
                ('balance', models.DateField(blank=True, max_length=255, null=True, verbose_name='BALANCE')),
                ('comments', models.TextField(blank=True, max_length=255, null=True, verbose_name='COMMENTS')),
                ('ward', models.DateField(blank=True, max_length=255, null=True, verbose_name='WARD')),
                ('longitude', models.DateField(blank=True, max_length=255, null=True, verbose_name='LONGITUDE')),
                ('latitude', models.DateField(blank=True, max_length=255, null=True, verbose_name='LATITUDE')),
                ('start_year', models.DateField(verbose_name='START_YEAR')),
                ('end_year', models.DateField(verbose_name='END_YEAR')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committees.Province')),
            ],
            options={
                'verbose_name': 'RELIEF MAIZE DISTRIBUTION',
                'verbose_name_plural': 'RELIEF MAIZE DISTRIBUTIONS',
            },
        ),
        migrations.CreateModel(
            name='SateliteCommittee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chairperson', models.CharField(blank=True, max_length=255, null=True, verbose_name='Chairperson')),
                ('vice_chairperson', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vice-Chairperson')),
                ('less_than_10_part_time_members', models.TextField(blank=True, null=True, verbose_name='Not more than Ten Part time Members')),
                ('trad_auth_repr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Traditional Authority Representative in Area')),
                ('atleast_3_disast_train_locals', models.TextField(blank=True, null=True, verbose_name='Atleast 3 Disaster Hazard Trained Locals')),
                ('commu_org', models.CharField(blank=True, max_length=255, null=True, verbose_name='Community Based Organization Representative')),
                ('local_commu_man_Repr_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Loca community Representative (Man)')),
                ('local_commu_man_Repr_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Loca community Representative (Man)')),
                ('local_commu_woman_Repr_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Loca community Representative (Woman)')),
                ('local_commu_woman_Repr_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Loca community Representative (Woman)')),
                ('youth_popu_repr', models.TextField(blank=True, null=True, verbose_name='Youth Population Representative(Atleast 1)')),
                ('businessman_farmer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Prominent Businessman or Farmer')),
                ('local_ngo_repr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Local NGO Representative')),
            ],
            options={
                'verbose_name': 'SATELITE COMMITTEE',
                'verbose_name_plural': 'SATELITE COMMITTEES',
            },
        ),
        migrations.CreateModel(
            name='TechnicalCommittee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Committee Name')),
                ('national_cordinator', models.CharField(max_length=255, verbose_name='National Co-ordinator (Chairperson)')),
                ('permernent_secretary', models.CharField(max_length=255, verbose_name='Permanent Secretary Responsible for Defence (Vice-Chairperson)')),
                ('ps_national_planning', models.CharField(max_length=255, verbose_name='Permanent Secreary Responsible for National Planning')),
                ('ps_local_government', models.CharField(max_length=255, verbose_name='Permanent Secreary Responsible for Local Government')),
                ('ps_home_affairs', models.CharField(max_length=255, verbose_name='Permanent Secreary Responsible for Home Affairs')),
                ('ps_health', models.CharField(max_length=255, verbose_name='Permanent Secreary Responsible for Health')),
                ('ps_energy', models.CharField(max_length=255, verbose_name='Permanent Secreary Responsible for Energy')),
                ('ps_agriculture', models.CharField(max_length=255, verbose_name='Permanent Secreary Responsible for Agriculture')),
                ('ps_environment_and_natural_resources', models.CharField(max_length=255, verbose_name='Permanent Secreary Responsible for Environment and Natural Resources')),
                ('ps_communications', models.CharField(max_length=255, verbose_name='Permanent Secreary Responsible for Communications')),
                ('ps_minerals_development', models.CharField(max_length=255, verbose_name='Permanent Secreary Responsible for Minerals Development')),
                ('ps_information_and_broadcasting', models.CharField(max_length=255, verbose_name='Permanent Secreary Responsible for Information and Broadcasting')),
                ('ps_community_development', models.CharField(max_length=255, verbose_name='Permanent Secreary Responsible for Community Development')),
                ('ps_works_and_supply', models.CharField(max_length=255, verbose_name='Permanent Secreary Responsible for Works and Supply')),
                ('red_cross_society', models.CharField(max_length=255, verbose_name='Zambia Red Cross Society Representative')),
                ('un_resident_coordinator', models.CharField(max_length=255, verbose_name='United Nations Resident Coordinator')),
                ('religious_organization_representative', models.CharField(max_length=255, verbose_name='religious organisation Representative')),
                ('ex_officio_member', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ex Officio Member Approved by the VP')),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committees.Ministry')),
            ],
            options={
                'verbose_name': 'TECHNICAL COMMITTEE',
                'verbose_name_plural': 'TECHNICAL COMMITTEES',
            },
        ),
        migrations.CreateModel(
            name='ZambiaVulnerabilityAssessmentCommittee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chairperson', models.CharField(blank=True, max_length=255, null=True, verbose_name='Chairperson')),
                ('Secretariat', models.CharField(blank=True, max_length=255, null=True, verbose_name='Secretariat')),
                ('less_than_10_part_time_members', models.TextField(blank=True, null=True, verbose_name='Not more than Ten Part time Members')),
                ('organizations_representatives', models.TextField(blank=True, null=True, verbose_name='Various Organizational Board Representatives')),
            ],
            options={
                'verbose_name': 'ZAMBIA VULNERABLITY ASSESSMENT COMMITTEE',
                'verbose_name_plural': 'ZAMBIA VULNERABLITY ASSESSMENT COMMITTEES',
            },
        ),
    ]
