# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0002_delete_maizerequisition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reliefmaizedistribution',
            name='access_point',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ACCESS POINT'),
        ),
        migrations.AlterField(
            model_name='reliefmaizedistribution',
            name='balance',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='BALANCE'),
        ),
        migrations.AlterField(
            model_name='reliefmaizedistribution',
            name='delivery_order_num',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DELIVERY ORDER #'),
        ),
        migrations.AlterField(
            model_name='reliefmaizedistribution',
            name='first_50_percent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='1st 50%'),
        ),
        migrations.AlterField(
            model_name='reliefmaizedistribution',
            name='first_50_percent_chq_num',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='1st 50%\\ CHQ #'),
        ),
        migrations.AlterField(
            model_name='reliefmaizedistribution',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='LATITUDE'),
        ),
        migrations.AlterField(
            model_name='reliefmaizedistribution',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='LONGITUDE'),
        ),
        migrations.AlterField(
            model_name='reliefmaizedistribution',
            name='mou_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='MOU AMOUNT'),
        ),
        migrations.AlterField(
            model_name='reliefmaizedistribution',
            name='mou_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='MOU NUMBER'),
        ),
        migrations.AlterField(
            model_name='reliefmaizedistribution',
            name='project_implemting_partner',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PROJECT IMPLEMENTING PARTNER'),
        ),
        migrations.AlterField(
            model_name='reliefmaizedistribution',
            name='second_50_percent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='2st 50%'),
        ),
        migrations.AlterField(
            model_name='reliefmaizedistribution',
            name='second_50_percent_chq_num',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='2st 50%\\ CHQ #'),
        ),
    ]
