# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0003_auto_20170524_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reliefmaizedistribution',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='reliefmaizedistribution',
            name='start_year',
        ),
        migrations.AlterField(
            model_name='reliefmaizedistribution',
            name='ward',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='WARD'),
        ),
    ]
