# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0005_auto_20170524_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reliefmaizedistribution',
            name='province',
            field=models.CharField(max_length=255),
        ),
    ]
